language: generic
sudo:required
services:
  - docker

before_install:
  - docker build -t balyan19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true balyan19/react-test npm test

after_success:
  - docker build -t balyan19/multi-client ./client
  - docker build -t balyan19/multi-nginx ./nginx
  - docker build -t balyan19/multi-server ./server
  - docker build -t balyan19/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin 

  - docker push balyan19/multi-client
  - docker push balyan19/multi-nginx
  - docker push balyan19/multi-server
  - docker push balyan19/multi-worker
